export const CREATE_PROJECT = 'CREATE_PROJECT';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
